- name: default value
  hosts: localhost
  tasks:
  - name: print default
    ansible.builtin.debug:
      msg: "Hello {{course | default('Ansible')}}"

- name: upper case
  hosts: localhost
  vars:
    greeting: "Hello, good morning"
  tasks:
  - name : convert into uppercase
    ansible.builtin.debug:
      msg: "{{greeting | upper}}"

- name: lower case
  hosts: localhost
  vars:
    greeting : "Hello , GOOD Morning"
  tasks:
  - name: conver into lower case
    ansible.builtin.debug:
      msg: "{{greeting | lower}}"