- name: default value
  hosts: localhost
  tasks:
  - name: print default
    ansible.builtin.debug:
      msg: "Hello {{course | default('Ansible')}}"

- name: upper case
  hosts: localhost
  vars:
    greeting: "Hello, good morning"
  - name : convert into uppercase
    ansible.builtin.debug:
      msg: "{{greeting | upper}}"